name: Black / Automaticly Triggered Python Autoformatter

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Find Changed Folder
      run: |
        git status
        # Get path of last file checked in
        pwd
        cd $GITHUB_WORKSPACE
        pwd
        LAST_PATH=$( git log --pretty="" --name-only -n 100 origin/master... -- | fgrep -v ".github" | head -1 )
        echo Last file modified: $LAST_PATH
        # Look for the main template file in this file's path or parents
        SAMPLEFOLDER_PATH=$( dirname "$LAST_PATH" )
        echo Last folder modified: $SAMPLEFOLDER_PATH
        TESTFOLDER_PATH=$SAMPLEFOLDER_PATH
        FOUNDFOLDER_PATH=
        while [ "$TESTFOLDER_PATH" != "." ]
        do
          echo "Looking for main template in $TESTFOLDER_PATH"
          MAINBICEP_PATH=$TESTFOLDER_PATH/main.bicep
          AZDEPLOYJSON_PATH=$TESTFOLDER_PATH/azuredeploy.json
          if [ -f "$MAINBICEP_PATH" ] || [ -f "$AZDEPLOYJSON_PATH" ]; then
            FOUNDFOLDER_PATH=$TESTFOLDER_PATH
            echo Found main template in $FOUNDFOLDER_PATH
            break
          fi
          TESTFOLDER_PATH=$( dirname "$TESTFOLDER_PATH" )
        done
        if [ ! $FOUNDFOLDER_PATH ]; then
            echo "Could not find main.bicep or azdeploy.json in folder or parents of $SAMPLEFOLDER_PATH" 1>&2
            exit 1
        fi
        echo "SAMPLEFOLDER_PATH=$FOUNDFOLDER_PATH" >> $GITHUB_ENV
        echo "MAINBICEP_PATH=$MAINBICEP_PATH" >> $GITHUB_ENV
        echo "AZDEPLOYJSON_PATH=$AZDEPLOYJSON_PATH" >> $GITHUB_ENV

    - name: Build main.bicep -> azuredeploy.json
      run: |
        if [ -f $MAINBICEP_PATH ]; then          
          echo Running: bicep build $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
          $BICEP_PATH build $MAINBICEP_PATH --outfile $AZDEPLOYJSON_PATH
        fi

    - name: Build main.bicep -> azuredeploy.json
      run: |
        dotnet tool install --global Azure.Bicep.RegistryModuleTool

        cd $SAMPLEFOLDER_PATH
        brm generate

    - name: Commit Changes
      run: |
        git config --global user.email "auto-bicep@noreply.github.com"
        git config --global user.name "Auto Bicep"

        git add $SAMPLEFOLDER_PATH

        if ! git diff-index --quiet HEAD --; then
          git commit -m "Autoformat with Black" --no-edit
          git push --force-with-lease
        fi
