# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Deploy ARM

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - id: create_storage
      uses: azure/CLI@v1
      env:
        resourceGroup: devops-resources
        location: eastus
        storageAccount: unrealddcdevopsstorage
        artifactContainer: artifacts
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az storage account show \
            --name "$storageAccount" \
            --resource-group "$resourceGroup" 2>/dev/null \
          || ${PWD}/scripts/prepareStorage.sh $resourceGroup $storageAccount $artifactContainer

    - id: upload_artifacts
      uses: azure/CLI@v1
      env:
        resourceGroup: devops-resources
        storageAccount: unrealddcdevopsstorage
        artifactContainer: artifacts
      with:
        azcliversion: 2.30.0
        inlineScript: |
          ${PWD}/scripts/package.sh $resourceGroup $storageAccount $artifactContainer

    - id: deploy_arm
      uses: azure/CLI@v1
      env:
        WORKING_DIR: marketplace/application/horde-storage/app-contents
        resourceGroup: devops-resources
        location: eastus
        storageAccount: unrealddcdevopsstorage
        artifactContainer: artifacts
      with:
        azcliversion: 2.30.0
        inlineScript: |
          ${PWD}/scripts/deployDev.sh $resourceGroup $storageAccount $artifactContainer $location $WORKING_DIR

    - id: cleanup_arm
      uses: azure/CLI@v1
      if: always()
      env:
        suffix: ${{ steps.deploy_arm.outputs.SUFFIX }}
      with:
        azcliversion: 2.30.0
        inlineScript: |
          echo Clean Up: devops-test-$suffix
          az group delete \
            --no-wait \
            --yes \
            --resource-group devops-test-$suffix
