# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
name: Deploy ARM

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  DeployTemplate:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: marketplace/application/horde-storage/app-contents
      resourceGroup: devops-resources
      location: eastus
      storageAccount: unrealddcdevopsstorage
      artifactContainer: artifacts
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: PrepareStorage
      run: |
        az storage account show \
          --name "$storageAccount" \
          --resource-group "$resourceGroup" 2>/dev/null \
        || ${PWD}/scripts/prepareStorage.sh $resourceGroup $storageAccount $artifactContainer

    - name: PackageApp
      run: |
        ${PWD}/scripts/package.sh $resourceGroup $storageAccount $artifactContainer

    - name: DeployARM
      id: deploy_arm
      run: |
        suffix=$RANDOM
        echo "SUFFIX=$suffix" >> $GITHUB_OUTPUT

        ${PWD}/scripts/deployDev.sh $resourceGroup $storageAccount $artifactContainer $location $WORKING_DIR $suffix

    - name: CleanupARM
      if: always()
      env:
        suffix: ${{ steps.deploy_arm.outputs.SUFFIX }}
      run: |
        echo Clean Up: devops-test-$suffix
        az group delete \
          --no-wait \
          --yes \
          --resource-group devops-test-$suffix
