name: On pull request

on:
  pull_request:
    branches:
      - main

jobs:
  get-module-to-validate:
    uses: ./.github/workflows/get-changed-module.yml

  validate-module-files:
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Adding a step to explicitly install the latest Bicep CLI because there is
      # always a delay in updating Bicep CLI in the job runner environments.
      - name: Install the latest Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
          bicep --version

      - name: Install Bicep registry module tool
        run: dotnet tool install --global Azure.Bicep.RegistryModuleTool

      - name: Validate module files
        run: brm validate
        working-directory: ${{ needs.get-module-to-validate.outputs.module_dir }}

  validate-non-module-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Check formatting
        run: npm run prettier:check

  validate-module-files-with-armttk:
    runs-on: ubuntu-latest
    needs: get-module-to-validate
    if: needs.get-module-to-validate.outputs.module_dir
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Bicep build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: "${{ needs.get-module-to-validate.outputs.module_dir }}/test/main.test.bicep"

      - name: Rename file for ARM TTK
        run: |
          cp "${{ needs.get-module-to-validate.outputs.module_dir }}/test/main.test.json" "${{ needs.get-module-to-validate.outputs.module_dir }}/test/mainTemplate.json"

      - name: Run ARM-TTK
        uses: microsoft/action-armttk@0.0.2
        with:
          workdir: ${{ needs.get-module-to-validate.outputs.module_dir }}/test/

